fun <T>print(items:ArrayList<T>){
    println(items.toString())
}
fun main(){
    val arrayList = ArrayList<Int>()
    arrayList.add(3)
    arrayList.add(7)
    arrayList.add(9)
    arrayList.add(2)
    arrayList.add(5)
    arrayList.add(5)
    arrayList.add(8)
    arrayList.add(5)
    arrayList.add(6)
    arrayList.add(3)
    arrayList.add(4)
    print(arrayList)
    val arrayList1 = ArrayList<Char>()
    arrayList1.add('A')
    arrayList1.add('D')
    arrayList1.add('o')
    arrayList1.add('w')
    arrayList1.add('B')
    arrayList1.add('k')
    arrayList1.add('G')
    arrayList1.add('M')
    arrayList1.add('x')
    print(arrayList1)
    val arrayList2 = ArrayList<String>()
    arrayList2.add("Samin")
    arrayList2.add("Sara")
    arrayList2.add("Amin")
    arrayList2.add("water")
    arrayList2.add("Baby")
    print(arrayList2)
}